#!/bin/bash
# Smart Test Strategy - brettstark-about
# Generated by create-qa-architect (Pro/Enterprise feature)
set -e

echo "🧠 Analyzing changes for optimal test strategy..."

# Environment variable overrides
if [[ "$SKIP_SMART" == "1" ]]; then
  echo "⚠️  SKIP_SMART=1 - Running comprehensive tests"
  npm run lint && npm run format:check && npm test
  exit 0
fi

if [[ "$FORCE_MINIMAL" == "1" ]]; then
  echo "⚪ FORCE_MINIMAL=1 - Running lint only"
  npm run lint && npm run format:check
  exit 0
fi

# Collect metrics
CHANGED_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null | wc -l | tr -d ' ')
CHANGED_LINES=$(git diff --stat HEAD~1..HEAD 2>/dev/null | tail -1 | grep -o '[0-9]* insertions' | grep -o '[0-9]*' || echo "0")
CURRENT_BRANCH=$(git branch --show-current)
HOUR=$(date +%H)
DAY_OF_WEEK=$(date +%u)

# Project-specific high-risk patterns (Personal Website)
HIGH_RISK_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null | grep -E "components/|lib/|app/" || true)
CONFIG_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null | grep -E "(package\.json|\.env|config|tsconfig)" || true)

# Calculate risk score (0-10)
RISK_SCORE=0

[[ -n "$HIGH_RISK_FILES" ]] && RISK_SCORE=$((RISK_SCORE + 3))
[[ -n "$CONFIG_FILES" ]] && RISK_SCORE=$((RISK_SCORE + 2))
[[ $CHANGED_FILES -gt 10 ]] && RISK_SCORE=$((RISK_SCORE + 2))
[[ $CHANGED_LINES -gt 200 ]] && RISK_SCORE=$((RISK_SCORE + 2))

case $CURRENT_BRANCH in
  main|master|production) RISK_SCORE=$((RISK_SCORE + 3)) ;;
  hotfix/*) RISK_SCORE=$((RISK_SCORE + 4)) ;;
esac

# Time pressure adjustment
HOUR_NUM=$((10#$HOUR))
if [[ $HOUR_NUM -ge 9 && $HOUR_NUM -le 17 && $DAY_OF_WEEK -le 5 ]]; then
  SPEED_BONUS=true
else
  SPEED_BONUS=false
fi

echo ""
echo "📊 Analysis Results:"
echo "   📁 Files changed: $CHANGED_FILES"
echo "   📏 Lines changed: $CHANGED_LINES"
echo "   🌿 Branch: $CURRENT_BRANCH"
echo "   🎯 Risk Score: $RISK_SCORE/10"
echo "   ⚡ Speed Bonus: $SPEED_BONUS"
echo ""

if [[ $RISK_SCORE -ge 5 ]]; then
  echo "🟡 MEDIUM+ RISK - Full validation"
  npm run lint && npm run format:check && npm test
elif [[ $RISK_SCORE -ge 2 || "$SPEED_BONUS" == "false" ]]; then
  echo "🟢 LOW RISK - Fast validation"
  npm run lint && npm run format:check
else
  echo "⚪ MINIMAL RISK - Quick check"
  npm run format:check
fi

echo ""
echo "💎 Smart Test Strategy powered by create-qa-architect Pro"
